# Generated by Django 5.2.16 on 2026-07-16 21:33

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('spotify_auth', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Album',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('spotify_album_id', models.CharField(max_length=128, unique=True)),
                ('name', models.CharField(max_length=255)),
                ('album_type', models.CharField(blank=True, max_length=32)),
                ('release_date', models.CharField(blank=True, max_length=32)),
                ('total_tracks', models.PositiveIntegerField(default=0)),
                ('image_url', models.URLField(blank=True, max_length=500)),
                ('spotify_url', models.URLField(blank=True, max_length=500)),
            ],
        ),
        migrations.CreateModel(
            name='Artist',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('spotify_artist_id', models.CharField(max_length=128, unique=True)),
                ('name', models.CharField(max_length=255)),
                ('genres', models.JSONField(blank=True, default=list)),
                ('popularity', models.PositiveSmallIntegerField(default=0)),
                ('image_url', models.URLField(blank=True, max_length=500)),
                ('spotify_url', models.URLField(blank=True, max_length=500)),
            ],
        ),
        migrations.CreateModel(
            name='Track',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('spotify_track_id', models.CharField(max_length=128, unique=True)),
                ('name', models.CharField(max_length=255)),
                ('duration_ms', models.PositiveIntegerField(default=0)),
                ('explicit', models.BooleanField(default=False)),
                ('popularity', models.PositiveSmallIntegerField(default=0)),
                ('preview_url', models.URLField(blank=True, max_length=500, null=True)),
                ('spotify_url', models.URLField(blank=True, max_length=500)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('album', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='tracks', to='listening.album')),
                ('artists', models.ManyToManyField(related_name='tracks', to='listening.artist')),
            ],
        ),
        migrations.CreateModel(
            name='Playlist',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('spotify_playlist_id', models.CharField(max_length=128)),
                ('owner_spotify_id', models.CharField(blank=True, max_length=128)),
                ('name', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True)),
                ('public', models.BooleanField(null=True)),
                ('collaborative', models.BooleanField(default=False)),
                ('total_tracks', models.PositiveIntegerField(default=0)),
                ('image_url', models.URLField(blank=True, max_length=500)),
                ('spotify_url', models.URLField(blank=True, max_length=500)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('spotify_account', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='playlists', to='spotify_auth.spotifyaccount')),
            ],
            options={
                'constraints': [models.UniqueConstraint(fields=('spotify_account', 'spotify_playlist_id'), name='unique_account_playlist')],
            },
        ),
        migrations.CreateModel(
            name='ListeningHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('played_at', models.DateTimeField()),
                ('context_type', models.CharField(blank=True, max_length=64)),
                ('context_uri', models.CharField(blank=True, max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('spotify_account', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='listening_history', to='spotify_auth.spotifyaccount')),
                ('track', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='plays', to='listening.track')),
            ],
            options={
                'ordering': ['-played_at'],
                'constraints': [models.UniqueConstraint(fields=('spotify_account', 'track', 'played_at'), name='unique_playback_event')],
            },
        ),
        migrations.CreateModel(
            name='UserTopArtist',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('time_range', models.CharField(choices=[('short_term', 'Short term'), ('medium_term', 'Medium term'), ('long_term', 'Long term')], max_length=16)),
                ('rank', models.PositiveSmallIntegerField()),
                ('fetched_at', models.DateTimeField(auto_now=True)),
                ('artist', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='listening.artist')),
                ('spotify_account', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='top_artists', to='spotify_auth.spotifyaccount')),
            ],
            options={
                'constraints': [models.UniqueConstraint(fields=('spotify_account', 'time_range', 'rank'), name='unique_top_artist_rank')],
            },
        ),
        migrations.CreateModel(
            name='UserTopTrack',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('time_range', models.CharField(choices=[('short_term', 'Short term'), ('medium_term', 'Medium term'), ('long_term', 'Long term')], max_length=16)),
                ('rank', models.PositiveSmallIntegerField()),
                ('fetched_at', models.DateTimeField(auto_now=True)),
                ('spotify_account', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='top_tracks', to='spotify_auth.spotifyaccount')),
                ('track', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='listening.track')),
            ],
            options={
                'constraints': [models.UniqueConstraint(fields=('spotify_account', 'time_range', 'rank'), name='unique_top_track_rank')],
            },
        ),
    ]
