# Generated by Django 5.2.16 on 2026-07-16 21:34

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('listening', '0001_initial'),
        ('spotify_auth', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='SavedTrack',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('added_at', models.DateTimeField()),
                ('spotify_account', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='saved_tracks', to='spotify_auth.spotifyaccount')),
                ('track', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='saved_by', to='listening.track')),
            ],
            options={
                'ordering': ['-added_at'],
                'constraints': [models.UniqueConstraint(fields=('spotify_account', 'track'), name='unique_saved_track')],
            },
        ),
    ]
