# Generated by Django 5.2.16 on 2026-07-16 21:33

import analytics.models
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('spotify_auth', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='WrappedShare',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('slug', models.SlugField(default=analytics.models.share_slug, max_length=64, unique=True)),
                ('period', models.CharField(default='yearly', max_length=16)),
                ('year', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('month', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('summary', models.JSONField(default=dict)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('spotify_account', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='wrapped_shares', to='spotify_auth.spotifyaccount')),
            ],
        ),
    ]
